Update README.md
zgzgorg/iam-backend pull request #73
Opened 2021-11-24 20:25 UTC by tslmy

2021-11-24 22:00 UTC, kis87988 commented
You may need to fix the CI with markdownlint https://app.codacy.com/gh/zgzgorg/iam-backend/pullRequest?prid=8466628&bid=26567206
and commitlint too.

2021-11-25 00:11 UTC, kis87988 requested changes

2021-11-25 00:11 UTC, kis87988 commented on README.md
> +Someone should've sent you an `iam_sqlite.cfg`. Place it under the repo's directory. Run:
This may not be very accurate but ok for now

2021-11-25 23:32 UTC, tslmy commented
Hard-wrapping lines does not work in the way I intended it to be. Shall we ignore the line length warnings?

2021-11-29 01:54 UTC, kis87988 approved these changes

2021-12-02 04:10 UTC, merged